name: build
on: push
env:
  slack_channel: terraform-module-azure-storage-sas
  golangci_lint_version: "v1.26"
jobs:
  validate:
    name: Validate and publish
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:

      - id: slack
        uses: voxmedia/github-action-slack-notify-build@v1
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        with:
          channel: ${{ env.slack_channel }}
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tflint
        run: docker run --rm -v $(pwd):/data -t wata727/tflint

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          args: --timeout=3m0s
          version: ${{ env.golangci_lint_version }}

      - name: go test
        run: go test ./...
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/master'
        uses: anothrNick/github-tag-action@1.22.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASES_BRANCHES: master
        id: bump_version

      - id: slack-success
        if: success() && github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ env.slack_channel }}
          status: SUCCESS
          color: good
          message_id: ${{ steps.slack.outputs.message_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - id: slack-failure
        if: failure() && github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ env.slack_channel }}
          status: FAILED
          color: danger
          message_id: ${{ steps.slack.outputs.message_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}